/**
 * The data-layer for a User
 * @module Users
 */

let mongoose = require('mongoose');
let bcrypt = require('bcrypt-nodejs');
let Schema = mongoose.Schema;

let userSchema = mongoose.Schema({
    favorites: [{ type : Schema.Types.ObjectId, ref: 'Publication' }],
    plan: {
        type: Number,
        testMonth: Boolean,
        publicationsAvailable: Number,
        expiration: Date
    },
    billing: {},
    local: {
        email: String,
        password: String,
        attempts: Number
    },
    facebook: {
        id: String,
        token: String,
        email: String,
        name: String
    },
    twitter: {
        id: String,
        token: String,
        displayName: String,
        username: String
    },
    google: {
        id: String,
        token: String,
        email: String,
        name: String
    }

});

/**
 * Id Hasg Generator
 *
 * @function generateHash
 * @memberof module:Users~User
 * @this module:Users~User
 * @param {String} password
 * @returns autogenerated hash to save as Id
 */
userSchema.methods.generateHash = function(password) {
    return bcrypt.hashSync(password, bcrypt.genSaltSync(8), null);
};

/**
 * Password validation
 *
 * @function validPassword
 * @memberof module:Users~User
 * @this module:Users~User
 * @param {string} password
 * @returns True or False
 */
userSchema.methods.validPassword = function(password) {
    return bcrypt.compareSync(password, this.local.password);
};


/**
 * A composition of user Facebook profile data and Facebook token data.
 * @typedef {Object}            Facebook
 * @property {string}           id            - Facebook user id of the user
 * @property {string}           token         - Facebook long lived token to access user information later
 * @property {string}           email         - Email of facebook user 
 * @property {string}           name          - Display name of facebook user
 */

/**
 * Details of the client Plan
 * @typedef {Object} Plan
 * @property {number}           type                    - Type of Plan (Bronze - Silver - Gold - Plantinum - Diamond)
 * @property {string}           testMonth               - Indicate is the actual month is test
 * @property {number}           publicationsAvailable   - Count of publications available 
 * @property {date}             expiration              - Date of publication expiration
 */

/**
 * Mongoose model for user document.
 *
 * @class User
 * @property {Plan}           plan                            - plan of the user
 * @property {Facebook}       facebook                        - Facebook information of the user
 */
module.exports = mongoose.model('User', userSchema);